# Production Environment Configuration
name: production
url: https://www.rebootmedia.net

# Protection rules
protection_rules:
  reviewers:
    - type: team
      name: senior-devs
    - type: team 
      name: devops-team
  wait_timer: 300  # 5 minute wait
  prevent_self_review: true
  required_deployment_branch: main

# Environment variables
variables:
  NODE_ENV: production
  LOG_LEVEL: info
  ENABLE_MONITORING: true
  PERFORMANCE_BUDGET_KB: 300
  ENABLE_SOURCE_MAPS: false
  ENABLE_COMPRESSION: true
  ENABLE_CACHING: true

# Deployment settings
deployment:
  auto_deploy: false  # Manual approval required
  blue_green: true
  rollback_enabled: true
  health_check_timeout: 600
  deployment_timeout: 1200
  traffic_ramp: 
    - percentage: 10
      duration: 300
    - percentage: 50
      duration: 600
    - percentage: 100
      duration: 0

# Quality gates (stricter for production)
quality_gates:
  required_checks:
    - typescript-compilation
    - eslint-validation
    - security-audit
    - unit-tests
    - integration-tests
    - e2e-tests
    - staging-deployment-success
  coverage_threshold: 80
  bundle_size_limit_kb: 300
  vulnerability_limit: 0
  performance_budget:
    lcp_ms: 2500
    fid_ms: 100
    cls: 0.10

# Security requirements
security:
  vulnerability_scan: mandatory
  security_headers_check: mandatory
  ssl_certificate_validation: mandatory
  dependency_audit: mandatory
  secrets_scan: mandatory

# Monitoring (comprehensive for production)
monitoring:
  health_check_interval: 60
  performance_monitoring: true
  error_tracking: true
  business_metrics: true
  uptime_monitoring: true
  synthetic_monitoring: true
  real_user_monitoring: true
  alert_channels:
    - pagerduty-production
    - slack-alerts-critical
    - email-oncall-team
    - sms-critical-alerts

# SLA requirements
sla:
  availability_target: 99.9
  response_time_p95_ms: 200
  response_time_p99_ms: 500
  error_rate_threshold: 0.1
  mttr_minutes: 15

# Feature flags
feature_flags:
  enable_ab_testing: true
  enable_performance_monitoring: true
  enable_error_boundaries: true
  enable_analytics: true
  enable_lead_scoring: true
  enable_marketing_attribution: true

# Rollback configuration
rollback:
  auto_rollback_conditions:
    - error_rate_percent: 1.0
      duration_minutes: 5
    - response_time_p95_ms: 1000
      duration_minutes: 10
    - availability_percent: 99.0
      duration_minutes: 2
  manual_rollback_time_limit_minutes: 5

# Compliance
compliance:
  gdpr_compliance: mandatory
  data_retention_policy: mandatory
  audit_logging: mandatory
  access_control: mandatory