# Reboot Media Production Alert Rules
# Comprehensive alerting for business metrics, performance, and infrastructure

groups:
  # Critical Business Impact Alerts
  - name: business_critical
    interval: 30s
    rules:
      - alert: SiteDown
        expr: |
          (
            sum(up{job=~"frontend.*"}) == 0
            or
            sum(up{job=~"backend.*"}) == 0
            or
            up{job="load-balancer"} == 0
          )
        for: 30s
        labels:
          severity: critical
          service: reboot-media
          team: sre
        annotations:
          summary: "Reboot Media website is completely down"
          description: "Website is unreachable. Immediate revenue impact expected."
          runbook_url: "https://runbooks.rebootmedia.net/site-down"
          revenue_impact: "High - Complete service unavailable"

      - alert: CriticalConversionDrop
        expr: |
          (
            rate(leads_submitted_total[1h]) < 
            (avg_over_time(rate(leads_submitted_total[1h] offset 24h)[7d]) * 0.3)
          )
        for: 15m
        labels:
          severity: critical
          team: marketing
          service: reboot-media
        annotations:
          summary: "Critical drop in lead conversions detected"
          description: "Lead conversion rate has dropped by >70% compared to 7-day average"
          runbook_url: "https://runbooks.rebootmedia.net/conversion-drop"
          revenue_impact: "Critical - Revenue generation severely impacted"
          current_value: "{{ $value | printf \"%.2f\" }} leads/hour"

      - alert: PaymentSystemDown
        expr: up{job="payment-processor"} == 0
        for: 1m
        labels:
          severity: critical
          service: reboot-media
          team: finance
        annotations:
          summary: "Payment processing system is down"
          description: "Cannot process payments. Revenue collection stopped."
          runbook_url: "https://runbooks.rebootmedia.net/payment-down"

  # Service Level Objectives (SLO) Alerts
  - name: slo_violations
    interval: 1m
    rules:
      - alert: AvailabilitySLOBreach
        expr: |
          (
            (
              sum(rate(http_requests_total{job=~"backend.*",code!~"5.."}[5m])) /
              sum(rate(http_requests_total{job=~"backend.*"}[5m]))
            ) < 0.995
          )
        for: 2m
        labels:
          severity: critical
          service: reboot-media
          team: sre
          slo: availability
        annotations:
          summary: "Availability SLO breach (99.5%)"
          description: "Service availability is {{ $value | humanizePercentage }}, below 99.5% SLO"
          runbook_url: "https://runbooks.rebootmedia.net/availability-slo"
          sla_breach: "true"

      - alert: LatencySLOBreach
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job=~"backend.*"}[5m])) by (le)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          service: reboot-media
          team: sre
          slo: latency
        annotations:
          summary: "Latency SLO breach (500ms P95)"
          description: "95th percentile response time is {{ $value | printf \"%.2f\" }}s, above 500ms SLO"
          runbook_url: "https://runbooks.rebootmedia.net/latency-slo"
          sla_breach: "true"

      - alert: ErrorRateSLOBreach
        expr: |
          (
            sum(rate(http_requests_total{job=~"backend.*",code=~"5.."}[5m])) /
            sum(rate(http_requests_total{job=~"backend.*"}[5m]))
          ) > 0.01
        for: 5m
        labels:
          severity: critical
          service: reboot-media
          team: sre
          slo: error_rate
        annotations:
          summary: "Error rate SLO breach (1%)"
          description: "Error rate is {{ $value | humanizePercentage }}, above 1% SLO"
          runbook_url: "https://runbooks.rebootmedia.net/error-rate-slo"
          sla_breach: "true"

  # Core Web Vitals Performance Alerts
  - name: core_web_vitals
    interval: 2m
    rules:
      - alert: CoreWebVitalsLCPDegraded
        expr: |
          histogram_quantile(0.75, 
            sum(rate(web_vitals_lcp_bucket[5m])) by (le)
          ) > 2500
        for: 5m
        labels:
          severity: warning
          team: frontend
          metric: lcp
        annotations:
          summary: "LCP (Largest Contentful Paint) degraded"
          description: "75th percentile LCP is {{ $value | printf \"%.0f\" }}ms, above 2.5s threshold"
          impact: "User experience degradation, potential SEO impact"
          runbook_url: "https://runbooks.rebootmedia.net/core-web-vitals"

      - alert: CoreWebVitalsCLSDegraded
        expr: |
          histogram_quantile(0.75,
            sum(rate(web_vitals_cls_bucket[5m])) by (le)
          ) > 0.1
        for: 5m
        labels:
          severity: warning
          team: frontend
          metric: cls
        annotations:
          summary: "CLS (Cumulative Layout Shift) degraded"
          description: "75th percentile CLS is {{ $value | printf \"%.3f\" }}, above 0.1 threshold"
          impact: "Poor visual stability, reduced user satisfaction"
          runbook_url: "https://runbooks.rebootmedia.net/core-web-vitals"

      - alert: CoreWebVitalsFIDDegraded
        expr: |
          histogram_quantile(0.75,
            sum(rate(web_vitals_fid_bucket[5m])) by (le)
          ) > 100
        for: 5m
        labels:
          severity: warning
          team: frontend
          metric: fid
        annotations:
          summary: "FID (First Input Delay) degraded"
          description: "75th percentile FID is {{ $value | printf \"%.0f\" }}ms, above 100ms threshold"
          impact: "Reduced interactivity, poor user experience"
          runbook_url: "https://runbooks.rebootmedia.net/core-web-vitals"

  # Business Intelligence Alerts
  - name: business_intelligence
    interval: 5m
    rules:
      - alert: ConversionRateTargetMiss
        expr: |
          (
            sum(rate(leads_submitted_total[1h])) /
            sum(rate(page_views_total{page="/contact"}[1h]))
          ) * 100 < 3
        for: 30m
        labels:
          severity: warning
          team: marketing
          kpi: conversion_rate
        annotations:
          summary: "Conversion rate below 3% target"
          description: "Current conversion rate is {{ $value | printf \"%.2f\" }}%, below 3% target"
          business_impact: "Revenue generation below target"
          runbook_url: "https://runbooks.rebootmedia.net/conversion-optimization"
          current_value: "{{ $value | printf \"%.2f\" }}%"
          threshold: "3%"

      - alert: LeadQualityScoreDrop
        expr: |
          avg(lead_quality_score) < 70
        for: 15m
        labels:
          severity: warning
          team: marketing
          kpi: lead_quality
        annotations:
          summary: "Average lead quality score below 70"
          description: "Average lead quality score is {{ $value | printf \"%.1f\" }}, below 70 threshold"
          business_impact: "Lower quality leads may reduce conversion to sales"
          runbook_url: "https://runbooks.rebootmedia.net/lead-quality"

      - alert: OrganicTrafficDrop
        expr: |
          (
            sum(rate(page_views_total{source="organic"}[1h])) <
            (avg_over_time(sum(rate(page_views_total{source="organic"}[1h] offset 24h))[7d]) * 0.7)
          )
        for: 2h
        labels:
          severity: warning
          team: seo
          channel: organic
        annotations:
          summary: "Significant drop in organic traffic"
          description: "Organic traffic down by >30% compared to 7-day average"
          business_impact: "Reduced visibility in search results"
          runbook_url: "https://runbooks.rebootmedia.net/seo-drop"

  # Infrastructure Health Alerts
  - name: infrastructure
    interval: 1m
    rules:
      - alert: HighCPUUsage
        expr: |
          100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          team: ops
          resource: cpu
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | printf \"%.1f\" }}% on {{ $labels.instance }}"
          runbook_url: "https://runbooks.rebootmedia.net/high-cpu"

      - alert: CriticalCPUUsage
        expr: |
          100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          team: ops
          resource: cpu
        annotations:
          summary: "Critical CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | printf \"%.1f\" }}% on {{ $labels.instance }}"
          runbook_url: "https://runbooks.rebootmedia.net/critical-cpu"

      - alert: HighMemoryUsage
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: ops
          resource: memory
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | printf \"%.1f\" }}% on {{ $labels.instance }}"
          runbook_url: "https://runbooks.rebootmedia.net/high-memory"

      - alert: DiskSpaceCritical
        expr: |
          (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 90
        for: 1m
        labels:
          severity: critical
          team: ops
          resource: disk
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Disk usage is {{ $value | printf \"%.1f\" }}% on {{ $labels.instance }}"
          runbook_url: "https://runbooks.rebootmedia.net/disk-space"

  # Security Monitoring Alerts
  - name: security
    interval: 1m
    rules:
      - alert: SuspiciousLoginActivity
        expr: rate(auth_failed_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          team: security
          threat: brute_force
        annotations:
          summary: "High rate of failed authentication attempts"
          description: "{{ $value | printf \"%.1f\" }} failed login attempts per second"
          runbook_url: "https://runbooks.rebootmedia.net/failed-auth"

      - alert: RateLimitingTriggered
        expr: rate(http_requests_total{code="429"}[1m]) > 10
        for: 2m
        labels:
          severity: warning
          team: security
          threat: dos
        annotations:
          summary: "High rate of rate-limited requests"
          description: "{{ $value | printf \"%.1f\" }} rate-limited requests per second"
          runbook_url: "https://runbooks.rebootmedia.net/rate-limiting"

      - alert: SSLCertificateExpiringSoon
        expr: (probe_ssl_earliest_cert_expiry - time()) / 86400 < 7
        for: 12h
        labels:
          severity: warning
          team: security
          resource: ssl_certificate
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | printf \"%.0f\" }} days"
          runbook_url: "https://runbooks.rebootmedia.net/ssl-renewal"

  # Application Performance Monitoring
  - name: application_performance
    interval: 1m
    rules:
      - alert: DatabaseConnectionPoolExhausted
        expr: db_connections_active / db_connections_max > 0.9
        for: 5m
        labels:
          severity: critical
          team: backend
          resource: database
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "{{ $value | humanizePercentage }} of database connections in use"
          runbook_url: "https://runbooks.rebootmedia.net/db-connections"

      - alert: APIEndpointHighLatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job=~"backend.*"}[5m])) 
            by (method, handler, le)
          ) > 2.0
        for: 5m
        labels:
          severity: warning
          team: backend
          resource: api_endpoint
        annotations:
          summary: "High latency on {{ $labels.method }} {{ $labels.handler }}"
          description: "95th percentile latency is {{ $value | printf \"%.2f\" }}s"
          runbook_url: "https://runbooks.rebootmedia.net/api-latency"

  # Lead Generation Performance Alerts
  - name: lead_generation
    interval: 5m
    rules:
      - alert: ContactFormErrorRate
        expr: |
          (
            sum(rate(form_submissions_total{form="contact",status="error"}[5m])) /
            sum(rate(form_submissions_total{form="contact"}[5m]))
          ) > 0.05
        for: 10m
        labels:
          severity: warning
          team: frontend
          form: contact
        annotations:
          summary: "High error rate on contact form"
          description: "Contact form error rate is {{ $value | humanizePercentage }}"
          business_impact: "Potential lead loss due to form submission failures"
          runbook_url: "https://runbooks.rebootmedia.net/form-errors"

      - alert: EmailDeliveryFailure
        expr: |
          (
            sum(rate(email_sent_total{status="failed"}[5m])) /
            sum(rate(email_sent_total[5m]))
          ) > 0.1
        for: 5m
        labels:
          severity: warning
          team: backend
          service: email
        annotations:
          summary: "High email delivery failure rate"
          description: "Email delivery failure rate is {{ $value | humanizePercentage }}"
          business_impact: "Lead nurturing and communication disrupted"
          runbook_url: "https://runbooks.rebootmedia.net/email-delivery"